[features]
seeds = false
skip-lint = false
[programs.localnet]
tbtc = "H5ZSi4XCPyktRH2vLT3eNq6vjZfxnmnkjH7MAGnApkRq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/dp/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
