name: Solidity docs (WIP) # TODO: Change name

on:
  pull_request:
  push:
    branches:
      - releases/mainnet/solidity/**
  release:
    types:
      - "published"
  workflow_dispatch:

jobs:
  docs-detect-changes:
    runs-on: ubuntu-latest
    outputs:
      path-filter: ${{ steps.filter.outputs.path-filter }}
    steps:
      - uses: actions/checkout@v3
        if: github.event_name == 'pull_request'
      - uses: dorny/paths-filter@v2
        if: github.event_name == 'pull_request'
        id: filter
        with:
          filters: |
            path-filter:
              - './solidity/contracts/**'
              - './.github/workflows/solidity-docs.yml'

  contracts-docs-build:
    name: Build contracts documentation
    needs: docs-detect-changes
    if: github.event_name == 'workflow_dispatch'
    uses: keep-network/tbtc-v2/.github/workflows/reusable-solidity-docs.yml@document-contracts #TODO: replace `@document-contracts` with `@main`
    with:
      projectSubfolder: /solidity
      # We need to remove unnecessary `//` comment used in the `@dev`
      # section of `BitcoinTx` documentation, which was causing problem with
      # rendering of the `.md` file. We do that by executing
      # `sed -i ':a;N;$!ba;s_///\n//\n_///\n_g'` on the problematic file. The
      # command substitutes `///` + newline + `//` + newline with just `///` +
      # newline and does this in a loop.
      preProcessingCommand: sed -i ':a;N;$!ba;s_///\n//\n_///\n_g' ./contracts/bridge/BitcoinTx.sol
      docName: tbtc-v2-contracts
      publish: false
      debug: true
    secrets:
      gcpServiceKeyBase64: ${{ secrets.THRESHOLD_API_DOCS_UPLOADER_SERVICE_KEY_BASE64 }}

  contracts-docs-publish-preview:
    name: Publish preview of contracts documentation
    needs: docs-detect-changes
    if: github.event_name == 'pull_request' || github.event_name == 'push'
    uses: keep-network/tbtc-v2/.github/workflows/reusable-solidity-docs.yml@document-contracts #TODO: replace `@document-contracts` with `@main`
    with:
      projectSubfolder: /solidity
      # We need to remove unnecessary `//` comment used in the `@dev`
      # section of `BitcoinTx` documentation, which was causing problem with
      # rendering of the `.md` file. We do that by executing
      # `sed -i ':a;N;$!ba;s_///\n//\n_///\n_g'` on the problematic file. The
      # command substitutes `///` + newline + `//` + newline with just `///` +
      # newline and does this in a loop.
      preProcessingCommand: sed -i ':a;N;$!ba;s_///\n//\n_///\n_g' ./contracts/bridge/BitcoinTx.sol
      docName: tbtc-v2-contracts
      publish: true
      gcpProject: keep-prd
      gcpBucketName: api-docs.threshold.network
      gcpBucketPath: solidity/${{ github.ref_name }}
      commentPR: true
    secrets:
      gcpServiceKeyBase64: ${{ secrets.THRESHOLD_API_DOCS_UPLOADER_SERVICE_KEY_BASE64 }}

  contracts-docs-publish:
    name: Publish contracts documentation
    needs: docs-detect-changes
    if: github.event_name == 'release' && startsWith(github.ref, 'refs/tags/solidity/')
    uses: keep-network/tbtc-v2/.github/workflows/reusable-solidity-docs.yml@document-contracts #TODO: replace `@document-contracts` with `@main`
    with:
      projectSubfolder: /solidity
      # We need to remove unnecessary `//` comment used in the `@dev`
      # section of `BitcoinTx` documentation, which was causing problem with
      # rendering of the `.md` file. We do that by executing
      # `sed -i ':a;N;$!ba;s_///\n//\n_///\n_g'` on the problematic file. The
      # command substitutes `///` + newline + `//` + newline with just `///` +
      # newline and does this in a loop.
      preProcessingCommand: sed -i ':a;N;$!ba;s_///\n//\n_///\n_g' ./contracts/bridge/BitcoinTx.sol
      docName: tbtc-v2-contracts
      publish: true
      gcpProject: keep-prd
      gcpBucketName: api-docs.threshold.network
      gcpBucketPath: solidity
    secrets:
      gcpServiceKeyBase64: ${{ secrets.THRESHOLD_API_DOCS_UPLOADER_SERVICE_KEY_BASE64 }}
